require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WebIssuesController do

  # This should return the minimal set of attributes required to create a valid
  # WebIssue. As you add validations to WebIssue, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WebIssuesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all web_issues as @web_issues" do
      web_issue = WebIssue.create! valid_attributes
      get :index, {}, valid_session
      assigns(:web_issues).should eq([web_issue])
    end
  end

  describe "GET show" do
    it "assigns the requested web_issue as @web_issue" do
      web_issue = WebIssue.create! valid_attributes
      get :show, {:id => web_issue.to_param}, valid_session
      assigns(:web_issue).should eq(web_issue)
    end
  end

  describe "GET new" do
    it "assigns a new web_issue as @web_issue" do
      get :new, {}, valid_session
      assigns(:web_issue).should be_a_new(WebIssue)
    end
  end

  describe "GET edit" do
    it "assigns the requested web_issue as @web_issue" do
      web_issue = WebIssue.create! valid_attributes
      get :edit, {:id => web_issue.to_param}, valid_session
      assigns(:web_issue).should eq(web_issue)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WebIssue" do
        expect {
          post :create, {:web_issue => valid_attributes}, valid_session
        }.to change(WebIssue, :count).by(1)
      end

      it "assigns a newly created web_issue as @web_issue" do
        post :create, {:web_issue => valid_attributes}, valid_session
        assigns(:web_issue).should be_a(WebIssue)
        assigns(:web_issue).should be_persisted
      end

      it "redirects to the created web_issue" do
        post :create, {:web_issue => valid_attributes}, valid_session
        response.should redirect_to(WebIssue.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved web_issue as @web_issue" do
        # Trigger the behavior that occurs when invalid params are submitted
        WebIssue.any_instance.stub(:save).and_return(false)
        post :create, {:web_issue => {}}, valid_session
        assigns(:web_issue).should be_a_new(WebIssue)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WebIssue.any_instance.stub(:save).and_return(false)
        post :create, {:web_issue => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested web_issue" do
        web_issue = WebIssue.create! valid_attributes
        # Assuming there are no other web_issues in the database, this
        # specifies that the WebIssue created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WebIssue.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => web_issue.to_param, :web_issue => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested web_issue as @web_issue" do
        web_issue = WebIssue.create! valid_attributes
        put :update, {:id => web_issue.to_param, :web_issue => valid_attributes}, valid_session
        assigns(:web_issue).should eq(web_issue)
      end

      it "redirects to the web_issue" do
        web_issue = WebIssue.create! valid_attributes
        put :update, {:id => web_issue.to_param, :web_issue => valid_attributes}, valid_session
        response.should redirect_to(web_issue)
      end
    end

    describe "with invalid params" do
      it "assigns the web_issue as @web_issue" do
        web_issue = WebIssue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WebIssue.any_instance.stub(:save).and_return(false)
        put :update, {:id => web_issue.to_param, :web_issue => {}}, valid_session
        assigns(:web_issue).should eq(web_issue)
      end

      it "re-renders the 'edit' template" do
        web_issue = WebIssue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WebIssue.any_instance.stub(:save).and_return(false)
        put :update, {:id => web_issue.to_param, :web_issue => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested web_issue" do
      web_issue = WebIssue.create! valid_attributes
      expect {
        delete :destroy, {:id => web_issue.to_param}, valid_session
      }.to change(WebIssue, :count).by(-1)
    end

    it "redirects to the web_issues list" do
      web_issue = WebIssue.create! valid_attributes
      delete :destroy, {:id => web_issue.to_param}, valid_session
      response.should redirect_to(web_issues_url)
    end
  end

end
